### ISSUE TITLE
Registration Page

### ISSUE THREAD

**Issue by Rittik-Biswal2000** [Developer-Student-Clubs-VSSUT-Burla/College-Comrade#16] opened 2021-03-12 17:45 UTC
The registration page should have the following components

1.Name
2.DOB
3.Email ID/password
4.Phone Number
5.Registration Number
6.Branch , Year , etc 
7. College Name (Preferably from a dropdown list)

**Comment by Rittik-Biswal2000** [comment] 2021-03-12 17:50
In the database store these details in the following tree structure

**college_name**
       **Year**
            **Branch**
                  Student details

**Comment by shreyadubey0902** [comment] 2021-03-12 18:40
I would like to work on it 
Can you please assign the work to me?

**Comment by rasikabakre** [comment] 2021-03-13 02:29
I really would like to work on the this issue. Would you kindly assign it to me?

**Comment by tanishq-123** [comment] 2021-03-14 16:10
I would like to help in implementing this, not done yet.

**Comment by vaibhav-c** [comment] 2021-03-15 13:00
There must be an option to upload a profile photo in the registration page which gets stored in Cloud Storage of Firebase. I would like to work on the same.

**Comment by Gautam204** [comment] 2021-03-16 07:34
In case the the issue is still open for others I would like to contribute in this project.  I am a participant in GSSOC'21. Please assign this issue to me.

**Comment by etamys** [comment] 2021-03-18 08:39
![Uploading Screenshot_2021-03-18-14-08-52-114_com.example.tt.jpg…]()

if it's open please check this.

**Comment by etamys** [comment] 2021-03-18 09:52
![Uploading Screenshot_2021-03-18-14-08-52-114_com.example.tt.jpg…]()
check this

**Comment by etamys** [comment] 2021-03-18 09:55
![Uploading Screenshot_2021-03-18-14-08-52-114_com.example.tt.jpg…]()
check this

**Comment by etamys** [comment] 2021-03-18 13:42
![Screenshot_2021-03-18-14-08-52-114_com example tt](https://user-images.githubusercontent.com/57357736/111635724-ce35e600-881d-11eb-915a-d80cca613f24.jpg)
check this

**Comment by AltamasBari** [comment] 2021-03-28 19:15
@etamys Send the PR asap.

**Comment by etamys** [comment] 2021-03-29 01:54
my code is ready i will upload it today after some changes, project-4admin I have a request, please be online. because bhaut logo ne issue create kiye h..I have also created some but you didn't answer. to mene aage work nhi kiya...

**Comment by etamys** [comment] 2021-03-29 03:07
hi
I tried to PR but it's shows me permission denied to etamys

**Comment by etamys** [comment] 2021-03-29 18:19
Hi
I did 
regex,
password hidden
scrollable


forgot btn is not good in Registration UI for this  ,I can this Desgin login UI  . I will make new PR for Login UI here forgot btn will look good

**Closed** 2021-04-25 12:27 UTC
Labels: GSSOC21, Level2
